spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adplat?characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root

#mybatis:
#  type-aliases-package: com.dewmobile.zc.excelsql.mapper
